#!/usr/bin/env bash
## ex.: make add-script SCRIPT_TYPE="MCryptExt"

set -e

# Include variables
source .docker/makefiles/variables.sh

# add scripts
case "${SCRIPT_TYPE}" in
  "MCryptExt")
    echo "Add ${GREEN}MCrypt extension${RESET}"
    make --no-print-directory replace-all-in-file FILE="${PHP_DOCKERFILE}" SEARCH="mcryptSupport" REPLACE="libmcrypt-dev"
    make --no-print-directory replace-all-in-file FILE="${PHP_DOCKERFILE}" SEARCH="mcryptInstall" REPLACE="RUN docker-php-ext-install mcrypt"
    ;;
  "BCMathExt")
    echo "Add ${GREEN}BCMath extension${RESET}"
    make --no-print-directory replace-all-in-file FILE="${PHP_DOCKERFILE}" SEARCH="bcmathInstall" REPLACE="RUN docker-php-ext-install bcmath"
    ;;
  * )
    echo "Invalid script ${RED}${SCRIPT_TYPE}${RESET}"
    ;;
esac
