#!/usr/bin/env bash
## ex.: make remove-script SCRIPT_TYPE="MCryptExt"

set -e

# Include variables
source .docker/makefiles/variables.sh

# remove scripts
case "${SCRIPT_TYPE}" in
  "MCryptExt")
    echo "Remove ${GREEN}MCrypt extension${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="mcryptSupport" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="mcryptInstall" FILE="${PHP_DOCKERFILE}"
    ;;
  "BCMathExt")
    echo "Remove ${GREEN}BCMath extension${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="bcmathInstall" FILE="${PHP_DOCKERFILE}"
    ;;
  "Mysql")
    echo "Remove ${GREEN}Mysql support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="mysqlExtensionsInstall" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="mysqlExtensionsEnable" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="MySQL" FILE="${ENV_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="MYSQL" FILE="${ENV_FILE}"
    ;;
  "Postgres")
    echo "Remove ${GREEN}Postgres support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="postgresExtensionsUpdate" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="postgresExtensionsPrerequisites" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="postgresExtensionsConfigure" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="postgresExtensionsInstall" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="PostgreSQL" FILE="${ENV_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="POSTGRES" FILE="${ENV_FILE}"
    ;;
  "Sqlite")
    echo "Remove ${GREEN}Sqlite support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="sqliteExtensionsUpdate" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="sqliteExtensionsPrerequisites" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="sqliteExtensionsInstall" FILE="${PHP_DOCKERFILE}"
    ;;
  "AllDBSupport")
      make --no-print-directory remove-script SCRIPT_TYPE="Mysql"
      make --no-print-directory remove-script SCRIPT_TYPE="Postgres"
      make --no-print-directory remove-script SCRIPT_TYPE="Sqlite"
      ;;
  "Redis")
    echo "Remove ${GREEN}Redis support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="Redis" FILE="${ENV_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="REDIS" FILE="${ENV_FILE}"
    ;;
  "PhpMyAdmin")
    echo "Remove ${GREEN}PhpMyAdmin support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="phpMyAdmin" FILE="${ENV_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="PMA" FILE="${ENV_FILE}"
    ;;
  "PhpPgAdmin")
    echo "Remove ${GREEN}PhpPgAdmin support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="phpPgAdmin" FILE="${ENV_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="PGA" FILE="${ENV_FILE}"
    ;;
  "PhpLiteAdmin")
    echo "Remove ${GREEN}PhpLiteAdmin support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="phpLiteAdmin" FILE="${ENV_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="PLA" FILE="${ENV_FILE}"
    ;;
  "AllDBTools")
    make --no-print-directory remove-script SCRIPT_TYPE="Redis"
    make --no-print-directory remove-script SCRIPT_TYPE="PhpMyAdmin"
    make --no-print-directory remove-script SCRIPT_TYPE="PhpPgAdmin"
    make --no-print-directory remove-script SCRIPT_TYPE="PhpLiteAdmin"
    ;;
  "MailSlurper")
    echo "Remove ${GREEN}MailSlurper support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="mailSlurper" FILE="${ENV_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="MAIL_SLURPER" FILE="${ENV_FILE}"
    ;;
  "MailCatcher")
    echo "Remove ${GREEN}MailCatcher support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="mailCatcher" FILE="${ENV_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="MAIL_CATCHER" FILE="${ENV_FILE}"
    ;;
  "MailHog")
    echo "Remove ${GREEN}MailHog support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="mailHog" FILE="${ENV_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="MAIL_HOG" FILE="${ENV_FILE}"
    ;;
  "AllMailSupport")
    make --no-print-directory remove-script SCRIPT_TYPE="MailSlurper"
    make --no-print-directory remove-script SCRIPT_TYPE="MailCatcher"
    make --no-print-directory remove-script SCRIPT_TYPE="MailHog"
    ;;
  "Php74")
    echo "Remove ${GREEN}Php 7.4 install${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="php74install" FILE="${PHP_DOCKERFILE}"
    ;;
  "Laravel")
    echo "Remove ${GREEN}Laravel support${RESET}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="mcryptSupport" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="mcryptInstall" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="bcmathInstall" FILE="${PHP_DOCKERFILE}"
    make --no-print-directory replace-all-in-file FILE="${NGINX_APP_CONF_FILE}" SEARCH="rootDefinition" REPLACE="root   /var/www;"
    make --no-print-directory delete-pattern-line-in-file PATTERN="xXSSOption" FILE="${NGINX_APP_CONF_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="xContent" FILE="${NGINX_APP_CONF_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="xFrameOption" FILE="${NGINX_APP_CONF_FILE}"
    make --no-print-directory replace-all-in-file FILE="${NGINX_APP_CONF_FILE}" SEARCH="indexDefinition" REPLACE="index  index.php index.html index.htm;"
    make --no-print-directory delete-pattern-line-in-file PATTERN="locationFavicon" FILE="${NGINX_APP_CONF_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="locationRobots" FILE="${NGINX_APP_CONF_FILE}"
    make --no-print-directory replace-all-in-file FILE="${NGINX_APP_S_CONF_FILE}" SEARCH="rootDefinition" REPLACE="root   /var/www;"
    make --no-print-directory delete-pattern-line-in-file PATTERN="xXSSOption" FILE="${NGINX_APP_S_CONF_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="xContent" FILE="${NGINX_APP_S_CONF_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="xFrameOption" FILE="${NGINX_APP_S_CONF_FILE}"
    make --no-print-directory replace-all-in-file FILE="${NGINX_APP_S_CONF_FILE}" SEARCH="indexDefinition" REPLACE="index  index.php index.html index.htm;"
    make --no-print-directory delete-pattern-line-in-file PATTERN="locationFavicon" FILE="${NGINX_APP_S_CONF_FILE}"
    make --no-print-directory delete-pattern-line-in-file PATTERN="locationRobots" FILE="${NGINX_APP_S_CONF_FILE}"
    ;;
  "AllApp")
    make --no-print-directory remove-script SCRIPT_TYPE="Laravel"
    ;;
  * )
    echo "Invalid script ${RED}${SCRIPT_TYPE}${RESET}"
    ;;
esac
