#!/usr/bin/env bash
## ex.: make replace-file-row FILE=.docker/build/php/Dockerfile SEARCH="mysqlExtensionsInstall" REPLACE="RUN docker-php-ext-install pdo pdo_mysql mysqli"

set -e

while IFS=$'\n' read -r p || [ -n "$p" ]
do
  if [[ $p == *${SEARCH}* ]]; then
    sed -i "s#$p#${REPLACE}#g" "${FILE}"
  fi
done < "${FILE}"
