#!/usr/bin/env bash
## ex.: make replace-all-in-file FILE=.docker/build/php/Dockerfile SEARCH="mysqlExtensionsInstall" REPLACE="RUN docker-php-ext-install pdo pdo_mysql mysqli"

set -e

sed -i "s#${SEARCH}#${REPLACE}#g" "${FILE}"
