version: '3'
services:

    #mailSlurper Service
    project-mailslurper:
        image: marcopas/docker-mailslurper
        container_name: project-mailslurper
        restart: unless-stopped
        ports:
            - "hostslurpersmtp"
            - "hostslurperwww"
            - "hostslurperservice"
        networks:
            - project-network

#Docker Networks
networks:
    project-network:
        driver: bridge