version: '3'
services:

    #mailCatcher Service
    project-mailcatcher:
        image: rordi/docker-mailcatcher
        container_name: project-mailcatcher
        restart: unless-stopped
        ports:
            - "hostcatchersmtp"
        networks:
            - project-network

#Docker Networks
networks:
    project-network:
        driver: bridge