version: '3'
services:

    #phpPgAdmin Service
    project-phppgadmin:
        image: dockage/phppgadmin:latest
        container_name: project-phppgadmin
        restart: unless-stopped
        ports:
            - "hostphppgadmin"
        environment:
            - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
            - PHP_PG_ADMIN_SERVER_HOST=phppgadminHost
            - PHP_PG_ADMIN_SERVER_PORT=5432
            - PHP_PG_ADMIN_SERVER_SSL_MODE=allow
            - PHP_PG_ADMIN_SERVER_DEFAULT_DB=phppgadminDb
            - PHP_PG_ADMIN_SERVER_PG_DUMP_PATH=/usr/bin/pg_dump
            - PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH=/usr/bin/pg_dumpall

            - PHP_PG_ADMIN_DEFAULT_LANG=auto
            - PHP_PG_ADMIN_AUTO_COMPLETE=default on
            - PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY=false
            - PHP_PG_ADMIN_OWNED_ONLY=false
            - PHP_PG_ADMIN_SHOW_COMMENTS=true
            - PHP_PG_ADMIN_SHOW_ADVANCED=false
            - PHP_PG_ADMIN_SHOW_SYSTEM=false
            - PHP_PG_ADMIN_MIN_PASSWORD_LENGTH=1
            - PHP_PG_ADMIN_LEFT_WIDTH=200
            - PHP_PG_ADMIN_THEME=default
            - PHP_PG_ADMIN_SHOW_OIDS=false
            - PHP_PG_ADMIN_MAX_ROWS=30
            - PHP_PG_ADMIN_MAX_CHARS=50
            - PHP_PG_ADMIN_USE_XHTML_STRICT=false
            - PHP_PG_ADMIN_HELP_BASE=http://www.postgresql.org/docs/%s/interactive/
            - PHP_PG_ADMIN_AJAX_REFRESH=3
        depends_on:
            - dbContainerName
        networks:
            - project-network

#Docker Networks
networks:
    project-network:
        driver: bridge