version: '3'
services:

    #Redis Service
    project-redis:
        image: redis:latest
        container_name: project-redis
        restart: unless-stopped
        ports:
            - "hostRedis"
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - project-redisdata:/data
        networks:
            - project-network

    #Redis Commander Service
    project-redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: project-redis-commander
        restart: unless-stopped
        ports:
            - "hostCommander"
        environment:
            - REDIS_HOSTS=local:project-redis:portRedis
            - HTTP_USER=redisUser
            - HTTP_PASSWORD=redisPassword
        depends_on:
            - project-redis
        networks:
            - project-network

#Docker Networks
networks:
    project-network:
        driver: bridge

#Docker Volumes
volumes:
    project-redisdata:
        driver: local