networks:
  project-network:
    driver: bridge
services:
  project-app:
    build:
      context: /home/tudor/projects/docker-lemp-boilerplate/docker/build/php
    container_name: project-app
    image: project/php
    networks:
      project-network: null
    restart: unless-stopped
    volumes:
    - /home/tudor/projects/docker-lemp-boilerplate/src:/var/www:rw
    - /home/tudor/projects/docker-lemp-boilerplate/docker/build/php/local.ini:/usr/local/etc/php/conf.d/local.ini:rw
    working_dir: /var/www
  project-webserver:
    build:
      context: /home/tudor/projects/docker-lemp-boilerplate/docker/build/nginx
    container_name: project-webserver
    image: project/nginx
    networks:
      project-network: null
    ports:
    - 8080:80/tcp
    - 443:443/tcp
    restart: unless-stopped
    volumes:
    - /home/tudor/projects/docker-lemp-boilerplate/src:/var/www:rw
    - /home/tudor/projects/docker-lemp-boilerplate/docker/build/nginx/conf.d/apps.conf:/etc/nginx/conf.d/apps.conf:rw
    - /home/tudor/projects/docker-lemp-boilerplate/docker/build/cert/project.local.pem:/etc/nginx/project.local.pem:rw
    - /home/tudor/projects/docker-lemp-boilerplate/docker/build/cert/project.local.key:/etc/nginx/project.local.key:rw
version: '3.0'

