version: '3'
services:

    #Nginx Service
    project-webserver:
        image: nginx:alpine
        container_name: project-webserver
        restart: unless-stopped
        ports:
            - "host80:80"
            - "host443:443"
        volumes:
            - ./../../src:/var/www
            - ./../../docker/build/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - project-network

#Docker Networks
networks:
    project-network:
        driver: bridge